name: Create Artifacts

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: |
          bun run random-number-generator.js
          bun run random-number-generator.js "test-seed"
          bun run random-number-generator.js 1906

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.txt

  build:
    name: Build Executables
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: ls -la random-number-generator-*

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: random-number-generator-executables
          path: random-number-generator-*

  test-linux:
    name: Test Linux Executable
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          name: random-number-generator-executables

      - run: chmod +x random-number-generator-linux

      - name: Run Linux tests
        run: |
          ./random-number-generator-linux
          ./random-number-generator-linux "test-seed"
          ./random-number-generator-linux 1906

      - name: Upload Linux test report
        uses: actions/upload-artifact@v4
        with:
          name: linux-test-report
          path: report.txt
