name: Demo – Actions, Arguments, Env Vars

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    env:
      APP_NAME: DemoApp
      ENVIRONMENT: Dev

    steps:
      # Step 1: Checkout current repository
      - name: Checkout current repo
        uses: actions/checkout@v4

      # Step 2: Checkout another repository USING ARGUMENTS (with)
      - name: Checkout Apache Tomcat repo
        uses: actions/checkout@v4
        with:
          repository: apache/tomcat
          ref: main
          path: tomcat

      # Step 3: Set up Java (action with arguments)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Step 4: Use environment variables
      - name: Print environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Java Version:"
          java -version

      # Step 5: List files to prove checkout worked
      - name: List workspace files
        run: |
          ls
          ls tomcat
