name: first

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Step 2 – Print message
        run: echo "Hello, world!"

      - name: Step 3 – Use environment variable
        env:
          MY_NAME: Tanishka
        run: echo "Hello $MY_NAME"
